### ISSUE TITLE
Grouping and horizontal scroll

### ISSUE THREAD

**Issue by rysep2** [DevExpress/Blazor#40]
Hi,

I tested the new grid grouping feature and noticed that when I use it with horizontal scroll, I don't see the show/hide grouping arrows. I added a sample application.
![2019-09-05 15_39_47-DevEx030Test](https://user-images.githubusercontent.com/8930481/64347257-e3f50900-cff3-11e9-8b6a-325127d99450.png)

[DevEx030Test.zip](https://github.com/DevExpress/Blazor/files/3579562/DevEx030Test.zip)

Cheers

**Comment by rysep2** [comment]
Also, the grid headers didn't line up in my sample when I removed the row widths. Am I doing something wrong?

![2019_09_05_16_05_10_DevEx030Test](https://user-images.githubusercontent.com/8930481/64349357-15bb9f00-cff7-11e9-8a98-e4ef95bcbf5b.png)

**Comment by SergeySeleznyov** [comment]
Hello @rysep2 ,
 
Thank you for reporting this!
I have reproduced this issue on my side and will fix it.
 
Until we provide the fix, you could avoid this issue by turning off scrollings (VirtualScrolling and Horizontal scrolling).
 
Please bear with us.

**Comment by SergeySeleznyov** [comment]
Workaround update:
 
Grouping arrows will appear if you apply the following styles:

```css
<style>
    th.dxbs-header-indent {
        width: 38px;
    }
    .dxgvArm > .dxbs-header-indent {
        font-size: 0;
    }
        .dxgvArm > .dxbs-header-indent > .invisible {
            height: 0;
        }
</style>
```
