### ISSUE TITLE
Form Layout - Custom item size calculation

### ISSUE THREAD

**Issue by bitdeploy** [DevExpress/Blazor#41]
Hey Guys,

I'm not sure if this is DevExpress Blazor Components related or a problem in general, but when I run the demo in Chrome or Edge the Form Layout Textboxes resize after the page is displayed.

[Link](https://user-images.githubusercontent.com/13085820/64423859-c6817700-d0a7-11e9-88a1-fa1a5571d45b.gif)

regards,
Michael

**Comment by SergeySeleznyov** [comment]
Hell @bitdeploy ,
 
Thank you for contacting us.
 
I have profiled this page and found that this delay is caused by the 3rd part demo code snippets highlighter we use in demos.
If have attached a screencast of how it works without the code snippet highlighter.
 
You can check it on your side. Just download the demos locally, and comment the following line:
 
https://github.com/DevExpress/Blazor/blob/ad21d0e207ec190dfd7f4355c2b920ac90bdb513/demo/BlazorDemo.ServerSide/BlazorDemo.ServerSide/Pages/CodeSnippets/CodeSnippet.razor#L18
 
It's unlikely that you will need the demos's code snippets.
  
We thought about replacing this client-side code highlighting with a static one.
When we have it done, this issue will disappear.
 
Thank you for drawing our attention to this task!

**Comment by bitdeploy** [comment]
Hi Sergey,

I would like to reopen this issue - I made another gif showing the problem. The input control is resizing/flickering after I switched the data. This only occurs if the CaptionPosition is set to Horizontal.

![blazor_textbox_resize_1](https://user-images.githubusercontent.com/13085820/66842142-11c25b80-ef6b-11e9-923c-1016eacd2d1c.gif)
![blazor_textbox_resize_2](https://user-images.githubusercontent.com/13085820/66842143-11c25b80-ef6b-11e9-8a1f-0996384bbee1.gif)

PS: I slowed down the playback of the gif...

**Comment by SergeySeleznyov** [comment]
Hi @bitdeploy,

You are welcome to reopen this issue.

**Comment by SergeySeleznyov** [comment]
Sorry, I just realized that you may not be able to reopen this issue.
I have done it.

**Comment by SergeySeleznyov** [comment]
The flickering comes from the form editors and label sizes calculations, that can be done only on client-side.
We can't avoid the size calculation since we need to find the widest label and then align the form according to it.
We will investigate if we can improve performance, but more probably we will just hide the client-side sizes calculation into some animation.
Would this solution suit you?

**Comment by bitdeploy** [comment]
Is it possible to disable the calculation by exposing a new DxFormLayout component parameter?

**Comment by SergeySeleznyov** [comment]
We will consider the possibility of implementing a solution without client-side calculation in the future.

In the meantime, I suggest you try the following workaround. Turn off the client initialization by overriding the component as follows:

```c#
namespace DevExpress.Blazor {
    public class FormLayoutWithoutClientSide : DxFormLayout {
        protected override Task InitClientSide(bool firstRender) {
            return Task.CompletedTask;
        }
    }
}
```

After that, use CSS to assign the parameters you want on the form layout. As the starting point, you can take the styles that the script generates.

For example, for the case when the widest label has "85px" width (just replace 85px with your value), all the labels will have the following styles:

```css
@media (min-width: 992px) {
	/*YOU MAY WANT TO IDENTIFY YOUR COMPONENT HERE*/ .dxbs-fl.form-horizontal .form-group > .dxbs-fl-cpt {
		width:85px;
	}
	/*YOU MAY WANT TO IDENTIFY YOUR COMPONENT HERE*/ .dxbs-fl.form-horizontal .form-group > .dxbs-fl-ctrl:not(img):not(.dxbs-fl-ctrl-nc) {
		width: calc(100% - 85px);
	}
	/*YOU MAY WANT TO IDENTIFY YOUR COMPONENT HERE*/ .dxbs-fl.form-horizontal .form-group > .dxbs-textbox:not(img):not(.dxbs-fl-ctrl-nc) {
		width: calc(100% - 85px);
	}
	/*YOU MAY WANT TO IDENTIFY YOUR COMPONENT HERE*/ .dxbs-fl.form-horizontal .form-group > .dxbs-dropdown-edit:not(img):not(.dxbs-fl-ctrl-nc) {
		width: calc(100% - 85px);
	}
	/*YOU MAY WANT TO IDENTIFY YOUR COMPONENT HERE*/ .dxbs-fl.form-horizontal .form-group > .dxbs-spin-edit:not(img):not(.dxbs-fl-ctrl-nc) {
		width: calc(100% - 85px);
	}
	/*YOU MAY WANT TO IDENTIFY YOUR COMPONENT HERE*/ .dxbs-fl.form-horizontal .row > div > .form-text {
		margin-left: 85px;
	}
}
```

Would you please try this approach in your project and let us know your results.
Thank you for your cooperation. We greatly appreciate this, Michael!
